# Generated by Django 5.2.11 on 2026-02-20 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
                ('chapter', models.CharField(db_index=True, max_length=2)),
                ('heading', models.CharField(blank=True, db_index=True, max_length=4)),
                ('subheading', models.CharField(blank=True, db_index=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='TradeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('trade_type', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export')], db_index=True, max_length=6)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('value_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hs_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='trade.hscode')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['year', 'month'], name='trade_trade_year_576232_idx'), models.Index(fields=['trade_type'], name='trade_trade_trade_t_7d6c32_idx'), models.Index(fields=['hs_code', 'year'], name='trade_trade_hs_code_5e7f30_idx'), models.Index(fields=['hs_code', 'trade_type'], name='trade_trade_hs_code_8fc35f_idx')],
            },
        ),
    ]
