# Generated by Django 5.2.11 on 2026-02-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tradedata',
            index=models.Index(fields=['country'], name='trade_trade_country_9b06da_idx'),
        ),
    ]
